layout_spectrum: 0.2489362
typography_spectrum: 0.1042553
color:
  lightness: 0
  brandStrength: 0.7694612
  saturation: 0.7659575
  rhythmicContrast: 0.717571
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
name: madslien
